// <auto-generated />
using System;
using FoodHeaven.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodHeaven.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260505105719_AddMoreDeals")]
    partial class AddMoreDeals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodHeaven.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlainPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("FoodHeaven.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("FoodHeaven.Models.DailyStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("int");

                    b.Property<int>("TotalReservations")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DailyStats");
                });

            modelBuilder.Entity("FoodHeaven.Models.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Deals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 5, 15, 57, 18, 103, DateTimeKind.Local).AddTicks(2187),
                            Description = "2 Royal Wagyu Burgers, 2 Spicy Thai Basil Pastas, and 4 Berry Smoothies.",
                            ImageUrl = "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
                            IsActive = true,
                            OriginalPrice = 82.00m,
                            Price = 59.99m,
                            Tag = "Family Choice",
                            Title = "Family Feast Bundle"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 5, 15, 57, 18, 103, DateTimeKind.Local).AddTicks(2199),
                            Description = "2 Truffle Risottos, 1 bottle of sparkling juice, and Fluffy Pancakes for two.",
                            ImageUrl = "https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800&q=80",
                            IsActive = true,
                            OriginalPrice = 61.50m,
                            Price = 45.00m,
                            Tag = "Popular",
                            Title = "Date Night Special"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 5, 15, 57, 18, 103, DateTimeKind.Local).AddTicks(2203),
                            Description = "Creamy Avocado Toast paired with a giant Berry Smoothie.",
                            ImageUrl = "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80",
                            IsActive = true,
                            OriginalPrice = 21.50m,
                            Price = 18.00m,
                            Tag = "Chef Special",
                            Title = "Healthy Morning Kick"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 5, 15, 57, 18, 103, DateTimeKind.Local).AddTicks(2207),
                            Description = "Mixed grill selection, 4 pieces of Seekh Kabab, 4 Tikka pieces, and 2 Garlic Naans.",
                            ImageUrl = "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
                            IsActive = true,
                            OriginalPrice = 45.00m,
                            Price = 34.99m,
                            Tag = "Hot Seller",
                            Title = "BBQ Lovers Platter"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 5, 15, 57, 18, 103, DateTimeKind.Local).AddTicks(2211),
                            Description = "Grilled Salmon, Golden Calamari, and Prawn Cocktail with a side of herb butter rice.",
                            ImageUrl = "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80",
                            IsActive = true,
                            OriginalPrice = 65.00m,
                            Price = 49.99m,
                            Tag = "Premium",
                            Title = "Seafood Extravaganza"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 5, 15, 57, 18, 103, DateTimeKind.Local).AddTicks(2214),
                            Description = "2 Continental Breakfast platters, 2 Iced Coffees, and 1 Dessert sampler.",
                            ImageUrl = "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=800&q=80",
                            IsActive = true,
                            OriginalPrice = 52.00m,
                            Price = 39.99m,
                            Tag = "Weekend Only",
                            Title = "Weekend Brunch for Two"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 5, 5, 15, 57, 18, 103, DateTimeKind.Local).AddTicks(2218),
                            Description = "Choose any 3 Pasta dishes and get a large Garlic Bread Supreme for free.",
                            ImageUrl = "https://images.unsplash.com/photo-1473093226795-af9932fe5856?w=800&q=80",
                            IsActive = true,
                            OriginalPrice = 55.00m,
                            Price = 42.00m,
                            Tag = "Value Deal",
                            Title = "Pasta Party Bundle"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 5, 5, 15, 57, 18, 103, DateTimeKind.Local).AddTicks(2222),
                            Description = "3 Classic Cheeseburgers, 3 Masala Fries, and 3 Coca Cola drinks.",
                            ImageUrl = "https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800&q=80",
                            IsActive = true,
                            OriginalPrice = 38.00m,
                            Price = 29.99m,
                            Tag = "Fast & Tasty",
                            Title = "Burger Madness"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 5, 5, 15, 57, 18, 103, DateTimeKind.Local).AddTicks(2226),
                            Description = "Molten Lava Cake, Triple Chocolate Cake, and 2 Vanilla Bean Ice Cream scoops.",
                            ImageUrl = "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=800&q=80",
                            IsActive = true,
                            OriginalPrice = 28.50m,
                            Price = 22.00m,
                            Tag = "Dessert King",
                            Title = "Sweet Tooth Combo"
                        });
                });

            modelBuilder.Entity("FoodHeaven.Models.LoyaltyAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LunchPunchCount")
                        .HasColumnType("int");

                    b.Property<string>("MembershipTier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LoyaltyAccounts");
                });

            modelBuilder.Entity("FoodHeaven.Models.LoyaltyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoyaltyAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyAccountId");

                    b.ToTable("LoyaltyTransactions");
                });

            modelBuilder.Entity("FoodHeaven.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Mains",
                            CreatedAt = new DateTime(2026, 5, 5, 15, 57, 18, 103, DateTimeKind.Local).AddTicks(1877),
                            Description = "Creamy arborio rice with fresh black truffles and parmesan crisp.",
                            ImageUrl = "/images/truffle_risotto.png",
                            IsAvailable = true,
                            Name = "Truffle Risotto",
                            Price = 24.00m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 128
                        },
                        new
                        {
                            Id = 2,
                            Category = "Mains",
                            CreatedAt = new DateTime(2026, 5, 5, 15, 57, 18, 103, DateTimeKind.Local).AddTicks(1906),
                            Description = "Atlantic salmon with lemon butter sauce and grilled asparagus.",
                            ImageUrl = "/images/platter_seafood.jpg",
                            IsAvailable = true,
                            Name = "Pan-Seared Salmon",
                            Price = 28.00m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 85
                        },
                        new
                        {
                            Id = 3,
                            Category = "Mains",
                            CreatedAt = new DateTime(2026, 5, 5, 15, 57, 18, 103, DateTimeKind.Local).AddTicks(1910),
                            Description = "Premium wagyu beef patty, aged cheddar, truffle mayo on brioche.",
                            ImageUrl = "/images/wagyu_burger.png",
                            IsAvailable = true,
                            Name = "Royal Wagyu Burger",
                            Price = 22.00m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 210
                        },
                        new
                        {
                            Id = 4,
                            Category = "Mains",
                            CreatedAt = new DateTime(2026, 5, 5, 15, 57, 18, 103, DateTimeKind.Local).AddTicks(1913),
                            Description = "Wagyu beef with truffle oil",
                            ImageUrl = "/images/truffle_burger.png",
                            IsAvailable = true,
                            Name = "Golden Truffle Burger",
                            Price = 18.50m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 95
                        },
                        new
                        {
                            Id = 5,
                            Category = "Mains",
                            CreatedAt = new DateTime(2026, 5, 5, 15, 57, 18, 103, DateTimeKind.Local).AddTicks(1917),
                            Description = "Fresh basil, chili, garlic",
                            ImageUrl = "/images/platter_italian.jpg",
                            IsAvailable = true,
                            Name = "Spicy Thai Basil Pasta",
                            Price = 14.00m,
                            Rating = 4.5,
                            ReviewCount = 67
                        },
                        new
                        {
                            Id = 6,
                            Category = "Starters",
                            CreatedAt = new DateTime(2026, 5, 5, 15, 57, 18, 103, DateTimeKind.Local).AddTicks(1920),
                            Description = "Sourdough, lemon, chili flakes",
                            ImageUrl = "/images/avocado_toast.png",
                            IsAvailable = true,
                            Name = "Creamy Avocado Toast",
                            Price = 12.00m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 143
                        },
                        new
                        {
                            Id = 7,
                            Category = "Drinks",
                            CreatedAt = new DateTime(2026, 5, 5, 15, 57, 18, 103, DateTimeKind.Local).AddTicks(1923),
                            Description = "Blueberry, banana, chia seeds",
                            ImageUrl = "/images/berry_smoothie.jpg",
                            IsAvailable = true,
                            Name = "Berry Smoothie",
                            Price = 9.50m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 88
                        },
                        new
                        {
                            Id = 8,
                            Category = "Healthy",
                            CreatedAt = new DateTime(2026, 5, 5, 15, 57, 18, 103, DateTimeKind.Local).AddTicks(1926),
                            Description = "Quinoa, chickpeas, tahini",
                            ImageUrl = "/images/platter_health.jpg",
                            IsAvailable = true,
                            Name = "Buddha Bowl",
                            Price = 11.00m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 72
                        },
                        new
                        {
                            Id = 9,
                            Category = "Desserts",
                            CreatedAt = new DateTime(2026, 5, 5, 15, 57, 18, 103, DateTimeKind.Local).AddTicks(1929),
                            Description = "Maple syrup, fresh berries",
                            ImageUrl = "/images/fluffy_pancakes.png",
                            IsAvailable = true,
                            Name = "Fluffy Pancakes",
                            Price = 13.50m,
                            Rating = 5.0,
                            ReviewCount = 156
                        });
                });

            modelBuilder.Entity("FoodHeaven.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Tax")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FoodHeaven.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Customization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FoodHeaven.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPremiumTable")
                        .HasColumnType("bit");

                    b.Property<int>("PartySize")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("ReservationTime")
                        .HasColumnType("time");

                    b.Property<string>("ReservationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("FoodHeaven.Models.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubscribedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("FoodHeaven.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FoodHeaven.Models.LoyaltyTransaction", b =>
                {
                    b.HasOne("FoodHeaven.Models.LoyaltyAccount", "LoyaltyAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("LoyaltyAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoyaltyAccount");
                });

            modelBuilder.Entity("FoodHeaven.Models.Order", b =>
                {
                    b.HasOne("FoodHeaven.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodHeaven.Models.OrderItem", b =>
                {
                    b.HasOne("FoodHeaven.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodHeaven.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FoodHeaven.Models.Reservation", b =>
                {
                    b.HasOne("FoodHeaven.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodHeaven.Models.LoyaltyAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FoodHeaven.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
