// <auto-generated />
using System;
using FoodHeaven.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodHeaven.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260113190705_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodHeaven.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 14, 0, 7, 3, 656, DateTimeKind.Local).AddTicks(3551),
                            Email = "admin@foodheaven.com",
                            FullName = "Admin User",
                            IsActive = true,
                            PasswordHash = "$2a$11$3qcw9IwtH0lKQgOgYhOLVerLvPILU7GtuopBQGAYABv4g1NNByILG",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("FoodHeaven.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("FoodHeaven.Models.LoyaltyAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LunchPunchCount")
                        .HasColumnType("int");

                    b.Property<string>("MembershipTier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LoyaltyAccounts");
                });

            modelBuilder.Entity("FoodHeaven.Models.LoyaltyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoyaltyAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyAccountId");

                    b.ToTable("LoyaltyTransactions");
                });

            modelBuilder.Entity("FoodHeaven.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Mains",
                            CreatedAt = new DateTime(2026, 1, 14, 0, 7, 3, 221, DateTimeKind.Local).AddTicks(5588),
                            Description = "Creamy arborio rice with fresh black truffles and parmesan crisp.",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuDd5A8E-n6CDlwtG-N9oKQBMrUU1ai9o8SrRvuciT7E6GHZVkZkh5-Zt16VeeNLYfVxEu31DlDNC0y1J4pW0-Z_pesr0YnifLq1es_rlR6cClkAqzAv-llsK4xuC4E2fg2lgfKdutgFROr7vmqj5z1GhIsp2C1u1qY8KKKYDoiCJ2KOYxa8-3VMtrGx2-dBCdswgHoluVdp0sywvXab14VKNb8E2C5CVi6aRH3v3GTeedd-ZjalrEO5Rk0ACBhwwF2Vm8nvzJO89A",
                            IsAvailable = true,
                            Name = "Truffle Risotto",
                            Price = 24.00m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 128
                        },
                        new
                        {
                            Id = 2,
                            Category = "Mains",
                            CreatedAt = new DateTime(2026, 1, 14, 0, 7, 3, 221, DateTimeKind.Local).AddTicks(5622),
                            Description = "Atlantic salmon with lemon butter sauce and grilled asparagus.",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuDNrvAofLcEQx3a1ZXD2766HUT65ZwhGPi1k1AXhl64HEavGi8nxRyffeK2LQ1oxPd2l434Oa94YXAZT12CMqKjQTBF2Jb-8E5dAceM7FJUcelHF-6c4q15awtGEgO3PLu8mQM5UI5IuBTsZxo8YpUNEtR4k4Z2U6u_W2XctSp_0D7ecrWJK422mSw0xZv6oUUGBnX3XTr0Y3po6FEJ-BVMbMMnqK4FYYNU0u4RQkSQXKzN3eFrWYD2bhYIjwKQERuzO1vUb6O07Q",
                            IsAvailable = true,
                            Name = "Pan-Seared Salmon",
                            Price = 28.00m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 85
                        },
                        new
                        {
                            Id = 3,
                            Category = "Mains",
                            CreatedAt = new DateTime(2026, 1, 14, 0, 7, 3, 221, DateTimeKind.Local).AddTicks(5631),
                            Description = "Premium wagyu beef patty, aged cheddar, truffle mayo on brioche.",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuCM8hth0W3ku6qprVWh1xDrJa96eDN2uJmaZhbfS7fRSEtLCI-EERTrdz-BRL9C8iHTTzjwDGDgWK6nzG7Zb-vTaz1LfTdwSREAtcsSBRZaO65TT3FBbJzniQHpeLnSCr7i4N755p3ym6gs7_N88CDD-p3XzQMkOjMCfLXpN6LAqnkeQMmtNvMGxA6uCkhJHvyGPIetRUXkjSf1XYDFL7WTIQpwCDWBSJ_aseXlg37sX-Ou2BWSObQzQn6bbuVbmvonnP15BXnnHg",
                            IsAvailable = true,
                            Name = "Royal Wagyu Burger",
                            Price = 22.00m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 210
                        },
                        new
                        {
                            Id = 4,
                            Category = "Mains",
                            CreatedAt = new DateTime(2026, 1, 14, 0, 7, 3, 221, DateTimeKind.Local).AddTicks(5637),
                            Description = "Wagyu beef with truffle oil",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuBShoqREj7Eta_asAkNTcCkk1CwuLWx_4mOsHB8W55cJus6vpIIVRedhO4m-xZHdV5U0KMmMwTM42xaZeGGtPGWWMW7SvOt8PEIaawXWyqY8_8hW6iVa9A9T4-xPiT3VtdlQBZCysVUjAStZN9Efm14MlHdnBz3ixPdg-wZY_ogVvqanOLkQqSYS1-jHMF7vUjKhwbFFhYNSMCHVPLcFVB8jJHN48-sWUpg0p4dLQUwOhxpfB43UnWXnd0zinLRewiAp-7okfgv1w",
                            IsAvailable = true,
                            Name = "Golden Truffle Burger",
                            Price = 18.50m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 95
                        },
                        new
                        {
                            Id = 5,
                            Category = "Mains",
                            CreatedAt = new DateTime(2026, 1, 14, 0, 7, 3, 221, DateTimeKind.Local).AddTicks(5643),
                            Description = "Fresh basil, chili, garlic",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuDfWitYE4hwDczx9Z-VIscp8kFY3t1c7tJueP_sW0XkR6EW2YM0vC1M4_LrFzbnykXuUg7lmcsy1nz-rL4x03gJfzB9iXMzCFJtTORYym8uJDHJbCoEygHqUJcYT59qBjkpnS3np4Zwu_KX8k8v1wrgeaTcao1EbDmNjz-ij4cjZFHcM-yo-cJIeTFaj2BOvoxkNCp5lu566DDOVAcqyZHIolGrMV4W-f9hRXH5a9eBfPjt2axi-Nvk3uFpAfFKy36vLmF4e1HOPQ",
                            IsAvailable = true,
                            Name = "Spicy Thai Basil Pasta",
                            Price = 14.00m,
                            Rating = 4.5,
                            ReviewCount = 67
                        },
                        new
                        {
                            Id = 6,
                            Category = "Starters",
                            CreatedAt = new DateTime(2026, 1, 14, 0, 7, 3, 221, DateTimeKind.Local).AddTicks(5650),
                            Description = "Sourdough, lemon, chili flakes",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuBOYQsBHIeCElObTIakyCRsUiWO6QpGn8r5oKaPTUg_WX1cNHiP0BFfIJ5HzdQO6No_7FGp14RCR6HZdWMUfcS6ndRpkmTFEcZCc6Vt2QUW4T7dOhil7MZLzI2Hh3bxHP7g_DFXGqwnB7_CulVLuE0qLiBvf1cw7k3HlWBxyW1OAWpdQ7GPM4R-mwOfCuni5crv1N0AT8WkSWowiW0dMKAJ1Ch1XIl-zEenjKvNoVHBxMkV7YGhwKjuOFOE6b7r02APVomuCJGDEQ",
                            IsAvailable = true,
                            Name = "Creamy Avocado Toast",
                            Price = 12.00m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 143
                        },
                        new
                        {
                            Id = 7,
                            Category = "Drinks",
                            CreatedAt = new DateTime(2026, 1, 14, 0, 7, 3, 221, DateTimeKind.Local).AddTicks(5657),
                            Description = "Blueberry, banana, chia seeds",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuB6wcyAKmNM9_xGQUed-hjbJioT5oPF1lfh6_YbyCXMg1W1ZmaCd888UKjOvluITeTAyZPMtsQLFPWIjDmcTA5L7-RIWceRR39xPbsEcpOodl0BlxDfLK7a83dW2hL-Qx5i1NIThF5cd7UWbJ-VPAHuHxYYpDg4vf7OvTOKGaOFEve1TWfFYLyjCXLKVbvORWtJXkb9sNMimTocvC86q0GPyCW192ZYAIMFQGCWGruiREfd_yXW2Sd6Szt5uHjg3W8cNgX14E-L_A",
                            IsAvailable = true,
                            Name = "Berry Smoothie",
                            Price = 9.50m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 88
                        },
                        new
                        {
                            Id = 8,
                            Category = "Healthy",
                            CreatedAt = new DateTime(2026, 1, 14, 0, 7, 3, 221, DateTimeKind.Local).AddTicks(5664),
                            Description = "Quinoa, chickpeas, tahini",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuAOWTa96d3PDsIuBSmkXVzVmNNqgO6qTsZbDREDQrB5WGTILshF9ZltdJbzZgh2JmYs1b04ng6cxGTfbFaI6Ov9Sri1Kj1a5dbbTs-az4YbGwjlttdjz8EwCI7kfNvUrLK0lG7Sa8ZA_38oTTK34NMlzahtTxf8D1IJC5nDJTxZ36ZoDhEiiZJJ0JNaI0FaLiI_2YGLWW27ocmtwBl9atsG6F9G4toUYoKJWYWsPljAHz2nAT4qcw7o4AF4UVQeXiKuN2p4bh79zQ",
                            IsAvailable = true,
                            Name = "Buddha Bowl",
                            Price = 11.00m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 72
                        },
                        new
                        {
                            Id = 9,
                            Category = "Desserts",
                            CreatedAt = new DateTime(2026, 1, 14, 0, 7, 3, 221, DateTimeKind.Local).AddTicks(5670),
                            Description = "Maple syrup, fresh berries",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuCJvopTQKId10fdUeMQuzlDbtvQ85tOjc6J4seYPjUawtAwEOKW0aMGXn1NC9fNWkMCe2GRhfET_cT4XmlZ6EeCIjOYqTU6nu8vcjeTETKNInnqkK75Aj4b-ceSA-bRgA3giVhp1rOdts1cps7OkBLsawGk8QEPgrVvfwRHbAm6kl7U-rtuPd2pa8QM9FFZihGy8G0lO0OQFXL2SWo5O5A4EIYyRFta6n5z5HZ6922sa9KQVl549BbGT5PVVFvYeR3Zh6iPMRGQpQ",
                            IsAvailable = true,
                            Name = "Fluffy Pancakes",
                            Price = 13.50m,
                            Rating = 5.0,
                            ReviewCount = 156
                        });
                });

            modelBuilder.Entity("FoodHeaven.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Tax")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FoodHeaven.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Customization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FoodHeaven.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartySize")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("ReservationTime")
                        .HasColumnType("time");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("FoodHeaven.Models.LoyaltyTransaction", b =>
                {
                    b.HasOne("FoodHeaven.Models.LoyaltyAccount", "LoyaltyAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("LoyaltyAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoyaltyAccount");
                });

            modelBuilder.Entity("FoodHeaven.Models.OrderItem", b =>
                {
                    b.HasOne("FoodHeaven.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodHeaven.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FoodHeaven.Models.LoyaltyAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FoodHeaven.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
